<?php

return [
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Nigiri Salmone",
    "slug" => "nigiri-salmone",
    "price" => 4,
    "visible" => 1,
    "description" => "Nigiri con salmone nostrano",
    "ingredients" => "riso, salmone",
    "image" => "https://images.unsplash.com/photo-1611810175440-aec1ef36d8c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
  ],
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Nigiri Tonno",
    "slug" => "nigiri-tonno",
    "price" => 4,
    "visible" => 1,
    "description" => "Nigiri con tonno nostrano",
    "ingredients" => "riso, tonno",
    "image" => "https://images.unsplash.com/photo-1625668742946-4ade4980c01e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
  ],
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Uramaki California",
    "slug" => "uramaki-california",
    "price" => 6,
    "visible" => 1,
    "description" => "Uramaki con Surimi, Tonno e Panna",
    "ingredients" => "riso, polpa di granchio, tonno, panna, ikura",
    "image" => "https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
  ],
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Temaki Spicy Salmon",
    "slug" => "temaki-spicy-salmon",
    "price" => 5,
    "visible" => 1,
    "description" => "Temaki con Salmone piccante",
    "ingredients" => "riso, salmone, avocado, tabasco",
    "image" => "https://www.giallozafferano.it/images/161-16180/Temaki-di-salmone_780x520_wm.jpg"
  ],
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Uramaki Salmone Avocado",
    "slug" => "uramaki-salmone-avocado",
    "price" => 8,
    "visible" => 1,
    "description" => "Uramaki classico",
    "ingredients" => "riso, salmone, avocado, alga nori",
    "image" => "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  ],
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Tempura di Gamberi",
    "slug" => "tempura-di-gamberi",
    "price" => 8,
    "visible" => 1,
    "description" => "Gamberi fritti",
    "ingredients" => "gamberi, panko",
    "image" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/tempura-di-gamberi.jpg?itok=-JjFZyK8"
  ],
  [
    "restaurant_id" => 1,
    "course_id" => 7,
    "name" => "Pollo Teriyaki",
    "slug" => "pollo-teriyaki",
    "price" => 7,
    "visible" => 1,
    "description" => "Pollo in salsa teriyaki",
    "ingredients" => "pollo, salsa teriyaki, cipollotto",
    "image" => "https://images.unsplash.com/photo-1609183480237-ccbb2d7c5772?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza Margherita",
    "slug" => "pizza-margherita",
    "price" => 6.00,
    "visible" => 1,
    "description" => "Pizza margherita",
    "ingredients" => "Pomodoro, mozzarella, basilico",
    "image" => "https://images.unsplash.com/photo-1564936281291-294551497d81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza con Salame Piccante",
    "slug" => "pizza-con-salame-piccante",
    "price" => 7.00,
    "visible" => 1,
    "description" => "Pizza con salame piccante",
    "ingredients" => "Pomodoro, mozzarella, basilico, salame piccante",
    "image" => "https://images.unsplash.com/photo-1605478371310-a9f1e96b4ff4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza con Salsiccia",
    "slug" => "pizza-con-salsiccia",
    "price" => 7.50,
    "visible" => 1,
    "description" => "Pizza con salsiccia",
    "ingredients" => "Pomodoro, mozzarella, basilico, salsiccia",
    "image" => "http://perfectitaliano.com.au/content/dam/perfectitaliano-aus/recipe/0_desktop/Desktop-Italian-Sausage-Pizza.jpg"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Focaccia",
    "slug" => "focaccia",
    "price" => 5.00,
    "visible" => 1,
    "description" => "Focaccia",
    "ingredients" => "Olio, rosmarino",
    "image" => "https://www.lamiabuonaforchetta.it/wp-content/uploads/2018/01/MG_1360.jpg"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza Napoli",
    "slug" => "pizza-napoli",
    "price" => 7.00,
    "visible" => 1,
    "description" => "Pizza Napoli",
    "ingredients" => "Pomodoro, mozzarella, alici, capperi",
    "image" => "https://www.donnamoderna.com/content/uploads/2021/08/pizza-napoli.jpg"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza Wurstel e Patatine",
    "slug" => "pizza-wurstel-e-patatine",
    "price" => 8.00,
    "visible" => 1,
    "description" => "Pizza Wurstel e Patatine",
    "ingredients" => "Pomodoro, mozzarella, Wurstel, Patatine",
    "image" => "http://www.scattidigusto.it/wp-content/uploads/2015/11/pizza-wurstel-patatine-pomodoro.jpg"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza Ortolana",
    "slug" => "pizza-ortolana",
    "price" => 8.00,
    "visible" => 1,
    "description" => "Pizza Ortolana",
    "ingredients" => "Fior di latte, Peperoni, Melanzane, Zucchine, Pomodori",
    "image" => "https://www.agrodolce.it/app/uploads/2018/01/pizza-ortolana-a1742-16.jpg"
  ],
  [
    "resturant_id" => 2,
    "course_id" => 7,
    "name" => "Pizza Tonno e Cipolla",
    "slug" => "pizza-tonno-e-cipolla",
    "price" => 8.00,
    "visible" => 1,
    "description" => "Pizza Tonno e Cipolla",
    "ingredients" => "Pomodori, Tonno, Cipolla, Basilico",
    "image" => "https://www.bofrost.it/writable/products/images-v2/15196.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 1,
    "name" => "Samosa di verdure",
    "slug" => "samosa-di-verdure",
    "price" => 2,
    "visible" => 1,
    "description" => "Involtini fritti con verdure speziate e legumi, 2pz",
    "ingredients" => "farina di ceci, patate, piselli, carote, legumi, spezie",
    "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2013/04/samosa-di-verdure.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 1,
    "name" => "Samosa di carne",
    "slug" => "samosa-di-carne",
    "price" => 2.50,
    "visible" => 1,
    "description" => "Involtini fritti con verdure speziate e carne, 2pz",
    "ingredients" => "farina di ceci, patate, carote, carne di manzo, carne di maiale, spezie",
    "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/826B4DC9-EB07-4C3B-83CE-026953D8741C/Derivates/C59CB804-46F8-4D02-B09F-65D270EB2601.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 1,
    "name" => "Palak Pakora",
    "slug" => "palak-pakora",
    "price" => 3.50,
    "visible" => 1,
    "description" => "Frittelle di ceci e spinaci, 5pz",
    "ingredients" => "farina di ceci, spinaci, spezie",
    "image" => "https://www.hookedonheat.com/wp-content/uploads/2020/11/Palak-Pyaaz-Pakoda-HOHV.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 1,
    "name" => "Falafel",
    "slug" => "falafel",
    "price" => 4.50,
    "visible" => 1,
    "description" => "Polpette di ceci e verdure, 4pz",
    "ingredients" => "ceci, verdure di stagione, spezie",
    "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/D036C31A-9CE0-4903-BF89-FC97B374DABF/Derivates/51d0a4e9-c4f5-4714-9cf5-26afeb270129.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 3,
    "name" => "Pollo Tikka Masala",
    "slug" => "pollo-tikka-masala",
    "price" => 8.50,
    "visible" => 1,
    "description" => "Bocconcini di pollo cotti in forno tandoori con yogurt, spezie e pomodoro",
    "ingredients" => "pollo, yogurt, spezie, pomodoro",
    "image" => "https://primochef.it/wp-content/uploads/2020/09/SH_pollo_tandoori.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 3,
    "name" => "Jhinga Curry",
    "slug" => "jhinga-curry",
    "price" => 8.50,
    "visible" => 1,
    "description" => "Gamberi in salsa al curry",
    "ingredients" => "gamberi, latte, spezie",
    "image" => "https://primochef.it/wp-content/uploads/2020/09/SH_pollo_tandoori.jpg"
  ],
  [
    "restaurant_id" => 3,
    "course_id" => 7,
    "name" => "Pollo al Mango con riso",
    "slug" => "pollo-al-mango-con-riso",
    "price" => 7.50,
    "visible" => 1,
    "description" => "Bocconcini di pollo cotti con salsa piccante al mango accompagnato da riso basmati",
    "ingredients" => "pollo, spezie, mango, riso",
    "image" => "https://www.vitamix.com/media/other/images/Vitamix-Mango-Sauce---Chicken-Square.jpg"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 1,
    "name" => "Guacamole con nachos",
    "slug" => "guacamole-con-nachos",
    "price" => 4,
    "visible" => 1,
    "description" => "Gustosa crema di avocado, pomodoro, cipolla e coriandolo fresco. Servita con croccanti triangoli di tortillas di mais. ",
    "ingredients" => "avocado, pomodoro, cipolla, chips di mais",
    "image" => "https://images.unsplash.com/photo-1523634700860-90d0ef74f137?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 1,
    "name" => "Tostadas de camaron",
    "slug" => "tostadas-de-camaron",
    "price" => 6,
    "visible" => 1,
    "description" => "Tortillas di mais fritta con crema di avocado, gamberi, pomodoro, cipolla e coriandolo",
    "ingredients" => "avocado, pomodoro, cipolla, tortilla di mais, gamberi",
    "image" => "https://dmn-dallas-news-prod.cdn.arcpublishing.com/resizer/iUyG7GEiQpfpVOKLAAWkt_L_1CA=/1660x934/smart/filters:no_upscale()/arc-anglerfish-arc2-prod-dmn.s3.amazonaws.com/public/2NMFEJ5H2IYA5EUZGX2PHQRLWQ.jpg"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 3,
    "name" => "Fajitas Combo",
    "slug" => "fajitas-combo",
    "price" => 8,
    "visible" => 1,
    "description" => "Striscioline di carne di manzo e pollo marinate in spezie messicane e cucinate con cipolle e peperoni",
    "ingredients" => "pollo, carne di manzo, cipolle, peperoni",
    "image" => "https://www.pedrosmadison.com/wp-content/uploads/2017/03/combo-fajitas-1170x679.jpg"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 7,
    "name" => "Burrito di carne",
    "slug" => "burrito-di-carne",
    "price" => 7,
    "visible" => 1,
    "description" => "",
    "ingredients" => "tortilla di farina bianca, pollo, carne di manzo, fagioli fritti",
    "image" => "https://www.melarossa.it/wp-content/uploads/2021/07/burrito-messicano-750x375.jpg?x75642"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 3,
    "name" => "Chili con carne",
    "slug" => "chili-con-carne",
    "price" => 8,
    "visible" => 1,
    "description" => "Chili con carne messicana",
    "ingredients" => "manzo macinato, pomodori, fagioli rossi",
    "image" => "https://assets.tmecosys.com/image/upload/t_web600x528/img/recipe/ras/Assets/4AABF349-67E4-44C5-9C07-153CF5897C3F/Derivates/4F81BC9B-DAD7-4887-B12B-0EC0C1935906.jpg"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 7,
    "name" => "Huevos rancheros",
    "slug" => "huevos-rancheros",
    "price" => 5,
    "visible" => 1,
    "description" => "",
    "ingredients" => "tortilla di mais, uova, fagioli neri, salsa di pomodoro",
    "image" => "https://bellyfull.net/wp-content/uploads/2021/04/Huevos-Rancheros-blog-768x1024.jpg"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 1,
    "name" => "Quesadilla",
    "slug" => "quesadilla",
    "price" => 6,
    "visible" => 1,
    "description" => "Con queso messicano originale",
    "ingredients" => "tortilla di mais, formaggio, pollo, peperoni",
    "image" => "https://cdn.ilclubdellericette.it/wp-content/uploads/2020/07/quesadillas-la-ricetta-originale-1200x630.jpg"
  ],
  [
    "restaurant_id" => 4,
    "course_id" => 5,
    "name" => "Churros con chocolate",
    "slug" => "churros-con-chocolate",
    "price" => 4,
    "visible" => 1,
    "description" => "",
    "ingredients" => "churros, cioccolata calda",
    "image" => "https://walnuts.org/wp-content/uploads/2017/09/e909bf5d1819a5d-963DFC89-EB32-4262-BD44F909E1100214-900x600.jpg"
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 1,
    "name" => "Tartare di manzo",
    "slug" => "tartare-di-manzo",
    "price" => 8,
    "visible" => 1,
    "description" => "tartare di manzo con tuorlo",
    "ingredients" => "150g di manzo, uovo, prezzemolo",
    "image" => "https://images.unsplash.com/photo-1612524681749-2f7615663729?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 1,
    "name" => "Polpo e patate",
    "slug" => "polpo-e-patate",
    "price" => 12,
    "visible" => 1,
    "description" => "Polpo e patate (contiene prodotti surgelati)",
    "ingredients" => "Polpo, patate, aglio, prezzemolo, limone, olive, pomodorini, olio extravergine d'oliva",
    "image" => "https://images.pexels.com/photos/10038710/pexels-photo-10038710.jpeg?cs=srgb&dl=pexels-valeria-boltneva-10038710.jpg&fm=jpg",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 2,
    "name" => "Pasta al pesto",
    "slug" => "pasta-al-pesto",
    "price" => 9,
    "visible" => 1,
    "description" => "Pasta al pesto secondo la tradizione genovese",
    "ingredients" => "Farfalle, pesto alla genovese",
    "image" => "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 2,
    "name" => "Pasta al salmone",
    "slug" => "pasta-al-salmone",
    "price" => 12,
    "visible" => 1,
    "description" => "Pasta al salmone fresco",
    "ingredients" => "Penne, panna, olio extravergine d'oliva, almone affumicato, prezzemolo, pepe nero",
    "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2013/03/penne-salmone.jpg",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 2,
    "name" => "Spaghetti al pomodoro",
    "slug" => "spaghetti-al-pomodoro",
    "price" => 8,
    "visible" => 1,
    "description" => "Un piatto simbolo della cucina italiana",
    "ingredients" => "Spaghetti, basilico, olio extravergine d'olive, pomodori pelati, aglio",
    "image" => "https://images.unsplash.com/photo-1612524681749-2f7615663729?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 3,
    "name" => "Calamari fritti",
    "slug" => "calamari-fritti",
    "price" => 12, 50,
    "visible" => 1,
    "description" => "Calamari fritti in olio disemi di arachide",
    "ingredients" => "Calamari, farina, sale fino",
    "image" => "https://images.unsplash.com/photo-1639024469010-44d77e559f7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 3,
    "name" => "Pollo al forno",
    "slug" => "pollo-al-forno",
    "price" => 10,
    "visible" => 1,
    "description" => "Pollo intero speziato al forno",
    "ingredients" => "Pollo, funghi, patate",
    "image" => "https://images.unsplash.com/photo-1611489142329-5f62cfa43e6e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 3,
    "name" => "Tagliata di mazo",
    "slug" => "tagliata-di-manzo",
    "price" => 15,
    "visible" => 1,
    "description" => "Tagliata di manzo alla griglia con rucola e scaglie di grana",
    "ingredients" => "Manzo, rucola, grana",
    "image" => "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 4,
    "name" => "Insalata mista",
    "slug" => "insalata-mista",
    "price" => 0,
    "visible" => 1,
    "description" => null,
    "ingredients" => "pomodori, cetrioli, carote, insalata",
    "image" => null, //https://cdn.pixabay.com/photo/2016/11/09/17/54/salad-1812349_1280.jpg
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 4,
    "name" => "Patatine fritte",
    "slug" => "patatine-fritte",
    "price" => 0,
    "visible" => 1,
    "description" => null,
    "ingredients" => "patate, sale fino",
    "image" => null, //https://images.unsplash.com/photo-1585109649139-366815a0d713?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Macedonia",
    "slug" => "macedonia",
    "price" => 4, 50,
    "visible" => 1,
    "description" => "Macedonia con frutta fresca",
    "ingredients" => "Kiwi, fragole, anguria, mirtilli, ciliegie, lamponi",
    "image" => "https://images.unsplash.com/photo-1519996529931-28324d5a630e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Tiramisù",
    "slug" => "tiramisu",
    "price" => 4,
    "visible" => 1,
    "description" => "Tiramisù fatto in casa",
    "ingredients" => "Mascarpone, savoiardi, caffè, uova, zucchero",
    "image" => "https://images.unsplash.com/photo-1631206753348-db44968fd440?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80",
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Acqua naturale",
    "slug" => "acqua-naturale",
    "price" => 1,
    "visible" => 1,
    "description" => null,
    "ingredients" => "Acqua naturale",
    "image" => null,
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Acqua frizzante",
    "slug" => "acqua-frizzante",
    "price" => 1,
    "visible" => 1,
    "description" => null,
    "ingredients" => "Acqua frizzante",
    "image" => null,
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Coca-cola",
    "slug" => "coca-cola",
    "price" => 2,
    "visible" => 1,
    "description" => null,
    "ingredients" => "Coca-cola",
    "image" => null,
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Beck's",
    "slug" => "becks",
    "price" => 3,
    "visible" => 1,
    "description" => "Birra Beck's da 33cl",
    "ingredients" => "Beck's",
    "image" => null,
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Vino rosso",
    "slug" => "vino-rosso",
    "price" => 12,
    "visible" => 1,
    "description" => "Vino rosso della casa",
    "ingredients" => "Vino rosso",
    "image" => null,
  ],
  [
    "restaurant_id" => 5,
    "course_id" => 5,
    "name" => "Vino bianco",
    "slug" => "vino-bianco",
    "price" => 12,
    "visible" => 1,
    "description" => "Vino bianco della casa",
    "ingredients" => "Vino bianco",
    "image" => null,
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Hamburger Americano",
    "slug" => "hamburger-americano",
    "price" => 7, 20,
    "visible" => 1,
    "description" => "Hamburger tipico americano con bacon e uovo (salse a scelta)",
    "ingredients" => "Manzo, bacon, uovo, insalata, pomodori, cetrioli sotto aceto, pane ai semi misti",
    "image" => "https://images.unsplash.com/photo-1550317138-10000687a72b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1220&q=80",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Hamburger di pesce",
    "slug" => "hamburger-di-pesce",
    "price" => 8, 20,
    "visible" => 1,
    "description" => "Hamburger di pesce con verdure (salse a scelta)",
    "ingredients" => "Merluzzo fritto, cipolla, insalata, pomodori, pane da hamburger",
    "image" => "https://images.unsplash.com/photo-1520073201527-6b044ba2ca9f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1312&q=80",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Double Ham",
    "slug" => "double-ham",
    "price" => 9,
    "visible" => 1,
    "description" => "Hamburger con 2 fette di manzo (salse a scelta)",
    "ingredients" => "Manzo, cipolla, insalata, pomodori, pane da hamburger, cheddar",
    "image" => "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1899&q=80",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Triple Ham",
    "slug" => "triple-ham",
    "price" => 11, 50,
    "visible" => 1,
    "description" => "Hamburger con 3 fette di manzo (salse a scelta)",
    "ingredients" => "Manzo, cipolla, insalata, pomodori, pane da hamburger, cheddar, cetrioli sotto aceto",
    "image" => "https://images.unsplash.com/photo-1552718752-c682d315b136?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1864&q=80",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Chicken Burger",
    "slug" => "chicken-burger",
    "price" => 7, 50,
    "visible" => 1,
    "description" => "Hamburger con pollo alla griglia (salse a scelta)",
    "ingredients" => "Pollo, insalata, pomodori, pane, cheddar",
    "image" => "https://images.pexels.com/photos/1624473/pexels-photo-1624473.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Egg Burger",
    "slug" => "egg-burger",
    "price" => 8, 50,
    "visible" => 1,
    "description" => "Hamburger con uovo e maiale alla piastra (salse a scelta)",
    "ingredients" => "Uovo, insalata, carne suina, cheddar, pane ai semi misti",
    "image" => "https://images.pexels.com/photos/6348082/pexels-photo-6348082.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Double Burger",
    "slug" => "double-burger",
    "price" => 10, 50,
    "visible" => 1,
    "description" => "Doppio hamburger di manzo (salse a scelta)",
    "ingredients" => "Manzo, insalata, pomodori, cheddar, cipolle, pane da hamburger",
    "image" => "https://images.pexels.com/photos/5948790/pexels-photo-5948790.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 7,
    "name" => "Burger con bacon",
    "slug" => "burger-con-bacon",
    "price" => 9, 50,
    "visible" => 1,
    "description" => "Hamburger di manzo con bacon (salse a scelta)",
    "ingredients" => "Manzo, cheddar, cipolle, cetrioli sotto aceto, bacon,  pane ai semi misti",
    "image" => "https://images.unsplash.com/photo-1598182198871-d3f4ab4fd181?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 4,
    "name" => "Patatine fritte",
    "slug" => "patatine-fritte-1",
    "price" => 0, 50,
    "visible" => 1,
    "description" => null,
    "ingredients" => "patate, sale fino",
    "image" => null, //https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 4,
    "name" => "Alette di pollo",
    "slug" => "alette-di-pollo",
    "price" => 1,
    "visible" => 1,
    "description" => null,
    "ingredients" => "pollo",
    "image" => null, //https://images.unsplash.com/photo-1426869981800-95ebf51ce900?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80
  ],

  [
    "restaurant_id" => 6,
    "course_id" => 5,
    "name" => "Acqua naturale",
    "slug" => "acqua-naturale-2",
    "price" => 1,
    "visible" => 1,
    "description" => null,
    "ingredients" => "Acqua naturale",
    "image" => null,
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 5,
    "name" => "Acqua frizzante",
    "slug" => "acqua-frizzante-2",
    "price" => 1,
    "visible" => 1,
    "description" => null,
    "ingredients" => "Acqua frizzante",
    "image" => null,
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 5,
    "name" => "Coca-cola",
    "slug" => "coca-cola-2",
    "price" => 2,
    "visible" => 1,
    "description" => null,
    "ingredients" => "Coca-cola",
    "image" => null,
  ],
  [
    "restaurant_id" => 6,
    "course_id" => 5,
    "name" => "Peroni",
    "slug" => "peroni",
    "price" => 2, 50,
    "visible" => 1,
    "description" => "Birra peroni da 33cl",
    "ingredients" => "peroni",
    "image" => null,
  ],
];