<?php

return [
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Nigiri Salmone",
        "slug" => "nigiri-salmone",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Nigiri con salmone nostrano",
        "ingredients" => "riso, salmone",
        "image" => "https://images.unsplash.com/photo-1611810175440-aec1ef36d8c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Nigiri Tonno",
        "slug" => "nigiri-tonno",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Nigiri con tonno nostrano",
        "ingredients" => "riso, tonno",
        "image" => "https://images.unsplash.com/photo-1625668742946-4ade4980c01e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Uramaki California",
        "slug" => "uramaki-california",
        "price" => 6.50,
        "visible" => 1,
        "description" => "Uramaki con Surimi, Tonno e Panna",
        "ingredients" => "riso, polpa di granchio, tonno, panna, ikura",
        "image" => "https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Temaki Spicy Salmon",
        "slug" => "temaki-spicy-salmon",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Temaki con Salmone piccante",
        "ingredients" => "riso, salmone, avocado, tabasco",
        "image" => "https://www.giallozafferano.it/images/161-16180/Temaki-di-salmone_780x520_wm.jpg"
    ],
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Uramaki Salmone Avocado",
        "slug" => "uramaki-salmone-avocado",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Uramaki classico",
        "ingredients" => "riso, salmone, avocado, alga nori",
        "image" => "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
    ],
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Tempura di Gamberi",
        "slug" => "tempura-di-gamberi",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Gamberi fritti",
        "ingredients" => "gamberi, panko",
        "image" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/tempura-di-gamberi.jpg?itok=-JjFZyK8"
    ],
    [
        "restaurant_id" => 1,
        "course_id" => 7,
        "name" => "Pollo Teriyaki",
        "slug" => "pollo-teriyaki",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pollo in salsa teriyaki",
        "ingredients" => "pollo, salsa teriyaki, cipollotto",
        "image" => "https://images.unsplash.com/photo-1609183480237-ccbb2d7c5772?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza Margherita",
        "slug" => "pizza-margherita",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pizza margherita",
        "ingredients" => "Pomodoro, mozzarella, basilico",
        "image" => "https://images.unsplash.com/photo-1564936281291-294551497d81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza con Salame Piccante",
        "slug" => "pizza-con-salame-piccante",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pizza con salame piccante",
        "ingredients" => "Pomodoro, mozzarella, basilico, salame piccante",
        "image" => "https://images.unsplash.com/photo-1605478371310-a9f1e96b4ff4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza con Salsiccia",
        "slug" => "pizza-con-salsiccia",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Pizza con salsiccia",
        "ingredients" => "Pomodoro, mozzarella, basilico, salsiccia",
        "image" => "http://perfectitaliano.com.au/content/dam/perfectitaliano-aus/recipe/0_desktop/Desktop-Italian-Sausage-Pizza.jpg"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Focaccia",
        "slug" => "focaccia",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Focaccia",
        "ingredients" => "Olio, rosmarino",
        "image" => "https://www.lamiabuonaforchetta.it/wp-content/uploads/2018/01/MG_1360.jpg"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza Napoli",
        "slug" => "pizza-napoli",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pizza Napoli",
        "ingredients" => "Pomodoro, mozzarella, alici, capperi",
        "image" => "https://www.donnamoderna.com/content/uploads/2021/08/pizza-napoli.jpg"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza Wurstel e Patatine",
        "slug" => "pizza-wurstel-e-patatine",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Pizza Wurstel e Patatine",
        "ingredients" => "Pomodoro, mozzarella, Wurstel, Patatine",
        "image" => "http://www.scattidigusto.it/wp-content/uploads/2015/11/pizza-wurstel-patatine-pomodoro.jpg"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza Ortolana",
        "slug" => "pizza-ortolana",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Pizza Ortolana",
        "ingredients" => "Fior di latte, Peperoni, Melanzane, Zucchine, Pomodori",
        "image" => "https://www.agrodolce.it/app/uploads/2018/01/pizza-ortolana-a1742-16.jpg"
    ],
    [
        "restaurant_id" => 2,
        "course_id" => 7,
        "name" => "Pizza Tonno e Cipolla",
        "slug" => "pizza-tonno-e-cipolla",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Pizza Tonno e Cipolla",
        "ingredients" => "Pomodori, Tonno, Cipolla, Basilico",
        "image" => "https://www.bofrost.it/writable/products/images-v2/15196.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 1,
        "name" => "Samosa di verdure",
        "slug" => "samosa-di-verdure",
        "price" => 2.00,
        "visible" => 1,
        "description" => "Involtini fritti con verdure speziate e legumi, 2pz",
        "ingredients" => "farina di ceci, patate, piselli, carote, legumi, spezie",
        "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2013/04/samosa-di-verdure.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 1,
        "name" => "Samosa di carne",
        "slug" => "samosa-di-carne",
        "price" => 2.50,
        "visible" => 1,
        "description" => "Involtini fritti con verdure speziate e carne, 2pz",
        "ingredients" => "farina di ceci, patate, carote, carne di manzo, carne di maiale, spezie",
        "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/826B4DC9-EB07-4C3B-83CE-026953D8741C/Derivates/C59CB804-46F8-4D02-B09F-65D270EB2601.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 1,
        "name" => "Palak Pakora",
        "slug" => "palak-pakora",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Frittelle di ceci e spinaci, 5pz",
        "ingredients" => "farina di ceci, spinaci, spezie",
        "image" => "https://www.hookedonheat.com/wp-content/uploads/2020/11/Palak-Pyaaz-Pakoda-HOHV.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 1,
        "name" => "Falafel",
        "slug" => "falafel",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Polpette di ceci e verdure, 4pz",
        "ingredients" => "ceci, verdure di stagione, spezie",
        "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/D036C31A-9CE0-4903-BF89-FC97B374DABF/Derivates/51d0a4e9-c4f5-4714-9cf5-26afeb270129.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 3,
        "name" => "Pollo Tikka Masala",
        "slug" => "pollo-tikka-masala",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Bocconcini di pollo cotti in forno tandoori con yogurt, spezie e pomodoro",
        "ingredients" => "pollo, yogurt, spezie, pomodoro",
        "image" => "https://primochef.it/wp-content/uploads/2020/09/SH_pollo_tandoori.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 3,
        "name" => "Jhinga Curry",
        "slug" => "jhinga-curry",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Gamberi in salsa al curry",
        "ingredients" => "gamberi, latte, spezie",
        "image" => "https://primochef.it/wp-content/uploads/2020/09/SH_pollo_tandoori.jpg"
    ],
    [
        "restaurant_id" => 3,
        "course_id" => 7,
        "name" => "Pollo al Mango con riso",
        "slug" => "pollo-al-mango-con-riso",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Bocconcini di pollo cotti con salsa piccante al mango accompagnato da riso basmati",
        "ingredients" => "pollo, spezie, mango, riso",
        "image" => "https://www.vitamix.com/media/other/images/Vitamix-Mango-Sauce---Chicken-Square.jpg"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 1,
        "name" => "Guacamole con nachos",
        "slug" => "guacamole-con-nachos",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Gustosa crema di avocado, pomodoro, cipolla e coriandolo fresco. Servita con croccanti triangoli di tortillas di mais. ",
        "ingredients" => "avocado, pomodoro, cipolla, chips di mais",
        "image" => "https://images.unsplash.com/photo-1523634700860-90d0ef74f137?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 1,
        "name" => "Tostadas de camaron",
        "slug" => "tostadas-de-camaron",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Tortillas di mais fritta con crema di avocado, gamberi, pomodoro, cipolla e coriandolo",
        "ingredients" => "avocado, pomodoro, cipolla, tortilla di mais, gamberi",
        "image" => "https://dmn-dallas-news-prod.cdn.arcpublishing.com/resizer/iUyG7GEiQpfpVOKLAAWkt_L_1CA=/1660x934/smart/filters:no_upscale()/arc-anglerfish-arc2-prod-dmn.s3.amazonaws.com/public/2NMFEJ5H2IYA5EUZGX2PHQRLWQ.jpg"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 3,
        "name" => "Fajitas Combo",
        "slug" => "fajitas-combo",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Striscioline di carne di manzo e pollo marinate in spezie messicane e cucinate con cipolle e peperoni",
        "ingredients" => "pollo, carne di manzo, cipolle, peperoni",
        "image" => "https://www.pedrosmadison.com/wp-content/uploads/2017/03/combo-fajitas-1170x679.jpg"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 7,
        "name" => "Burrito di carne",
        "slug" => "burrito-di-carne",
        "price" => 7.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "tortilla di farina bianca, pollo, carne di manzo, fagioli fritti",
        "image" => "https://www.melarossa.it/wp-content/uploads/2021/07/burrito-messicano-750x375.jpg?x75642"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 3,
        "name" => "Chili con carne",
        "slug" => "chili-con-carne",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Chili con carne messicana",
        "ingredients" => "manzo macinato, pomodori, fagioli rossi",
        "image" => "https://assets.tmecosys.com/image/upload/t_web600x528/img/recipe/ras/Assets/4AABF349-67E4-44C5-9C07-153CF5897C3F/Derivates/4F81BC9B-DAD7-4887-B12B-0EC0C1935906.jpg"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 7,
        "name" => "Huevos rancheros",
        "slug" => "huevos-rancheros",
        "price" => 5.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "tortilla di mais, uova, fagioli neri, salsa di pomodoro",
        "image" => "https://bellyfull.net/wp-content/uploads/2021/04/Huevos-Rancheros-blog-768x1024.jpg"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 1,
        "name" => "Quesadilla",
        "slug" => "quesadilla",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Con queso messicano originale",
        "ingredients" => "tortilla di mais, formaggio, pollo, peperoni",
        "image" => "https://cdn.ilclubdellericette.it/wp-content/uploads/2020/07/quesadillas-la-ricetta-originale-1200x630.jpg"
    ],
    [
        "restaurant_id" => 4,
        "course_id" => 5,
        "name" => "Churros con chocolate",
        "slug" => "churros-con-chocolate",
        "price" => 4.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "churros, cioccolata calda",
        "image" => "https://walnuts.org/wp-content/uploads/2017/09/e909bf5d1819a5d-963DFC89-EB32-4262-BD44F909E1100214-900x600.jpg"
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 1,
        "name" => "Tartare di manzo",
        "slug" => "tartare-di-manzo",
        "price" => 8.50,
        "visible" => 1,
        "description" => "tartare di manzo con tuorlo",
        "ingredients" => "150g di manzo, uovo, prezzemolo",
        "image" => "https://images.unsplash.com/photo-1612524681749-2f7615663729?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 1,
        "name" => "Polpo e patate",
        "slug" => "polpo-e-patate",
        "price" => 12.00,
        "visible" => 1,
        "description" => "Polpo e patate (contiene prodotti surgelati)",
        "ingredients" => "Polpo, patate, aglio, prezzemolo, limone, olive, pomodorini, olio extravergine d'oliva",
        "image" => "https://images.pexels.com/photos/10038710/pexels-photo-10038710.jpeg?cs=srgb&dl=pexels-valeria-boltneva-10038710.jpg&fm=jpg",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 2,
        "name" => "Pasta al pesto",
        "slug" => "pasta-al-pesto",
        "price" => 9.00,
        "visible" => 1,
        "description" => "Pasta al pesto secondo la tradizione genovese",
        "ingredients" => "Farfalle, pesto alla genovese",
        "image" => "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 2,
        "name" => "Pasta al salmone",
        "slug" => "pasta-al-salmone",
        "price" => 12.00,
        "visible" => 1,
        "description" => "Pasta al salmone fresco",
        "ingredients" => "Penne, panna, olio extravergine d'oliva, almone affumicato, prezzemolo, pepe nero",
        "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2013/03/penne-salmone.jpg",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 2,
        "name" => "Spaghetti al pomodoro",
        "slug" => "spaghetti-al-pomodoro",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Un piatto simbolo della cucina italiana",
        "ingredients" => "Spaghetti, basilico, olio extravergine d'olive, pomodori pelati, aglio",
        "image" => "https://images.unsplash.com/photo-1612524681749-2f7615663729?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 3,
        "name" => "Calamari fritti",
        "slug" => "calamari-fritti",
        "price" => 12.50,
        "visible" => 1,
        "description" => "Calamari fritti in olio disemi di arachide",
        "ingredients" => "Calamari, farina, sale fino",
        "image" => "https://images.unsplash.com/photo-1639024469010-44d77e559f7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 3,
        "name" => "Pollo al forno",
        "slug" => "pollo-al-forno",
        "price" => 10.00,
        "visible" => 1,
        "description" => "Pollo intero speziato al forno",
        "ingredients" => "Pollo, funghi, patate",
        "image" => "https://images.unsplash.com/photo-1611489142329-5f62cfa43e6e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 3,
        "name" => "Tagliata di mazo",
        "slug" => "tagliata-di-manzo",
        "price" => 15.00,
        "visible" => 1,
        "description" => "Tagliata di manzo alla griglia con rucola e scaglie di grana",
        "ingredients" => "Manzo, rucola, grana",
        "image" => "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 4,
        "name" => "Insalata mista",
        "slug" => "insalata-mista",
        "price" => 1.50,
        "visible" => 1,
        "description" => null,
        "ingredients" => "pomodori, cetrioli, carote, insalata",
        "image" => "https://cdn.pixabay.com/photo/2016/11/09/17/54/salad-1812349_1280.jpg"
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 4,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte",
        "price" => 2.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "patate, sale fino",
        "image" => "https://images.unsplash.com/photo-1585109649139-366815a0d713?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 5,
        "name" => "Macedonia",
        "slug" => "macedonia",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Macedonia con frutta fresca",
        "ingredients" => "Kiwi, fragole, anguria, mirtilli, ciliegie, lamponi",
        "image" => "https://images.unsplash.com/photo-1519996529931-28324d5a630e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 5,
        "name" => "Tiramisù",
        "slug" => "tiramisu",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Tiramisù fatto in casa",
        "ingredients" => "Mascarpone, savoiardi, caffè, uova, zucchero",
        "image" => "https://images.unsplash.com/photo-1631206753348-db44968fd440?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 6,
        "name" => "Acqua naturale",
        "slug" => "acqua-naturale",
        "price" => 1.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua naturale",
        "image" => null,
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 5,
        "name" => "Acqua frizzante",
        "slug" => "acqua-frizzante",
        "price" => 1.50,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua frizzante",
        "image" => null,
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 6,
        "name" => "Coca-cola",
        "slug" => "coca-cola",
        "price" => 2.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Coca-cola",
        "image" => null,
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 5,
        "name" => "Beck's",
        "slug" => "becks",
        "price" => 3.00,
        "visible" => 1,
        "description" => "Birra Beck's da 33cl",
        "ingredients" => "Beck's",
        "image" => null,
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 6,
        "name" => "Vino rosso",
        "slug" => "vino-rosso",
        "price" => 12.00,
        "visible" => 1,
        "description" => "Vino rosso della casa 1lt",
        "ingredients" => "Vino rosso",
        "image" => null,
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 6,
        "name" => "Vino bianco",
        "slug" => "vino-bianco",
        "price" => 12.00,
        "visible" => 1,
        "description" => "Vino bianco della casa 1lt",
        "ingredients" => "Vino bianco",
        "image" => null,
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Hamburger Americano",
        "slug" => "hamburger-americano",
        "price" => 7.20,
        "visible" => 1,
        "description" => "Hamburger tipico americano con bacon e uovo (salse a scelta)",
        "ingredients" => "Manzo, bacon, uovo, insalata, pomodori, cetrioli sotto aceto, pane ai semi misti",
        "image" => "https://images.unsplash.com/photo-1550317138-10000687a72b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1220&q=80",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Hamburger di pesce",
        "slug" => "hamburger-di-pesce",
        "price" => 8.20,
        "visible" => 1,
        "description" => "Hamburger di pesce con verdure (salse a scelta)",
        "ingredients" => "Merluzzo fritto, cipolla, insalata, pomodori, pane da hamburger",
        "image" => "https://images.unsplash.com/photo-1520073201527-6b044ba2ca9f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1312&q=80",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Double Ham",
        "slug" => "double-ham",
        "price" => 9.50,
        "visible" => 1,
        "description" => "Hamburger con 2 fette di manzo (salse a scelta)",
        "ingredients" => "Manzo, cipolla, insalata, pomodori, pane da hamburger, cheddar",
        "image" => "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1899&q=80",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Triple Ham",
        "slug" => "triple-ham",
        "price" => 11.50,
        "visible" => 1,
        "description" => "Hamburger con 3 fette di manzo (salse a scelta)",
        "ingredients" => "Manzo, cipolla, insalata, pomodori, pane da hamburger, cheddar, cetrioli sotto aceto",
        "image" => "https://images.unsplash.com/photo-1552718752-c682d315b136?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1864&q=80",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Chicken Burger",
        "slug" => "chicken-burger",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Hamburger con pollo alla griglia (salse a scelta)",
        "ingredients" => "Pollo, insalata, pomodori, pane, cheddar",
        "image" => "https://images.pexels.com/photos/1624473/pexels-photo-1624473.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Egg Burger",
        "slug" => "egg-burger",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Hamburger con uovo e maiale alla piastra (salse a scelta)",
        "ingredients" => "Uovo, insalata, carne suina, cheddar, pane ai semi misti",
        "image" => "https://images.pexels.com/photos/6348082/pexels-photo-6348082.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Double Burger",
        "slug" => "double-burger",
        "price" => 10.50,
        "visible" => 1,
        "description" => "Doppio hamburger di manzo (salse a scelta)",
        "ingredients" => "Manzo, insalata, pomodori, cheddar, cipolle, pane da hamburger",
        "image" => "https://images.pexels.com/photos/5948790/pexels-photo-5948790.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 7,
        "name" => "Burger con bacon",
        "slug" => "burger-con-bacon",
        "price" => 9.50,
        "visible" => 1,
        "description" => "Hamburger di manzo con bacon (salse a scelta)",
        "ingredients" => "Manzo, cheddar, cipolle, cetrioli sotto aceto, bacon,  pane ai semi misti",
        "image" => "https://images.unsplash.com/photo-1598182198871-d3f4ab4fd181?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 4,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-2",
        "price" => 1.50,
        "visible" => 1,
        "description" => null,
        "ingredients" => "patate, sale fino",
        "image" => "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 4,
        "name" => "Alette di pollo",
        "slug" => "alette-di-pollo",
        "price" => 2.20,
        "visible" => 1,
        "description" => null,
        "ingredients" => "pollo",
        "image" => "https://images.unsplash.com/photo-1426869981800-95ebf51ce900?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"
    ],

    [
        "restaurant_id" => 6,
        "course_id" => 6,
        "name" => "Acqua naturale",
        "slug" => "acqua-naturale-2",
        "price" => 1.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua naturale",
        "image" => null,
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 6,
        "name" => "Acqua frizzante",
        "slug" => "acqua-frizzante-2",
        "price" => 1.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua frizzante",
        "image" => null,
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 5,
        "name" => "Coca-cola",
        "slug" => "coca-cola-2",
        "price" => 2.20,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Coca-cola",
        "image" => null,
    ],
    [
        "restaurant_id" => 6,
        "course_id" => 6,
        "name" => "Peroni",
        "slug" => "peroni",
        "price" => 2.50,
        "visible" => 1,
        "description" => "Birra Peroni da 33cl",
        "ingredients" => "peroni",
        "image" => null,
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 6,
        "name" => "Peroni",
        "slug" => "peroni-2",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Birra Peroni da 33cl",
        "ingredients" => "peroni",
        "image" => "https://i.ibb.co/wB9n6KG/peroni.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 6,
        "name" => "Moretti",
        "slug" => "moretti",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Birra Moretti da 33cl",
        "ingredients" => "birra Moretti",
        "image" => "https://i.ibb.co/NVTdxCb/moretti.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 5,
        "name" => "Coca Cola",
        "slug" => "coca-cola-3",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Coca Cola da 33cl",
        "ingredients" => "Coca Cola",
        "image" => "https://i.ibb.co/5vrF5yT/coca-cola-lattina.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 1,
        "name" => "Bruschetta al pomodoro",
        "slug" => "bruschetta-pomodoro",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Bruschetta di pane fresco con pomodori Ciliegini",
        "ingredients" => "Pane fresco, pomodorini, olio, basilico",
        "image" => "https://i.ibb.co/stbspPq/bruschetta-al-pomodoro.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 1,
        "name" => "Funghi ripieni",
        "slug" => "funghi-ripieni",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Funghi champignon ripieni, porsione da 4 pz",
        "ingredients" => "Funghi champignon, olio, pane, Grana Padano",
        "image" => "https://i.ibb.co/HxJ0h1j/funghi-ripieni.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 2,
        "name" => "Spaghetti allo scoglio",
        "slug" => "spaghetti-allo-scoglio",
        "price" => 9.00,
        "visible" => 1,
        "description" => "Spaghetti allo scoglio",
        "ingredients" => "Spaghetti, gamberi, cozze, vongole, pomodori ciliegino",
        "image" => "https://i.ibb.co/wShGkW4/spaghetti-allo-scoglio-bianco.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 3,
        "name" => "Arrosticini",
        "slug" => "arrosticini",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Arrosticini di pecora",
        "ingredients" => "Carne di pecora, rosmarino",
        "image" => "https://i.ibb.co/5xN8hZ9/arrosticini.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 4,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-3",
        "price" => 2.50,
        "visible" => 1,
        "description" => "Patatine fritte una porzione",
        "ingredients" => "Patate",
        "image" => "https://i.ibb.co/X8RWnVP/patatine-fritte-1.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 7,
        "name" => "Pizza margherita",
        "slug" => "pizza-margherita-2",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Pizza margherita con mozzarella fresca",
        "ingredients" => "Mozzarella, pomodoro, basilico",
        "image" => "https://i.ibb.co/MDDfDhq/pizza-margherita-1.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 7,
        "name" => "Pizza marinara",
        "slug" => "pizza-marinara",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Pizza marinara",
        "ingredients" => "Pomodoro, aglio, origano, olio",
        "image" => "https://i.ibb.co/jTDCcGs/pizza-marinara.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza quattro stagioni",
        "slug" => "pizza-quattro-stagioni",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pizza quattro stagioni",
        "ingredients" => "Mozzarella, origano, pomodoro, carciofini, olive nere, prosciutto",
        "image" => "https://i.ibb.co/qpD3mfX/pizza-capricciosa.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza quattro formaggi",
        "slug" => "pizza-quattro-formaggi",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Pizza quattro formaggi",
        "ingredients" => "Stracchino, la mozzarella, il gorgonzola e il parmigiano reggiano",
        "image" => "https://i.ibb.co/3vt1QhC/pizza-quattro-formaggi.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza con le patate",
        "slug" => "pizza-con-patate",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Pizza con le patate",
        "ingredients" => "Mozzarella, patate, rosmarino",
        "image" => "https://i.ibb.co/BjJm4SY/Pizza-Mozzarella-e-Rosmarino-Fotor.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza alla diavola",
        "slug" => "pizza-diavola",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Pizza alla diavola",
        "ingredients" => "Mozzarella, pomodoro, salame piccante",
        "image" => "https://i.ibb.co/b2gHGGS/pizza-diavola.png",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza margherita",
        "slug" => "pizza-margherita-3",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Pizza margherita",
        "ingredients" => "Mozzarella, pomodoro, basilico",
        "image" => "https://i.ibb.co/5k7tYqH/pizza-margherita.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza margherita senza glutine",
        "slug" => "pizza-margherita-senza-glutine",
        "price" => 6.50,
        "visible" => 1,
        "description" => "Pizza margherita senza glutine",
        "ingredients" => "Mozzarella, pomodoro, basilico, farina di farro",
        "image" => "https://i.ibb.co/5k7tYqH/pizza-margherita.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 7,
        "name" => "Pizza campagnola",
        "slug" => "pizza-campagnola",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pizza campagnola",
        "ingredients" => "Fiori di zucca, pomodorini essiccati, basilico, olive nere",
        "image" => "https://i.ibb.co/ZNggCQz/pizza-campagnola.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 4,
        "name" => "Patatine fritte con wurstel",
        "slug" => "patatine-fritte-wurstel",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Patatine fritte con wursteluna porzione",
        "ingredients" => "Patate, wurstel",
        "image" => "https://i.ibb.co/XDWf21X/patatine-fritte-wurstel.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 6,
        "name" => "Coca Cola",
        "slug" => "coca-cola-4",
        "price" => 4.50,
        "visible" => 1,
        "description" => "coca cola bottiglia da 1.5lt",
        "ingredients" => "Coca Cola",
        "image" => "https://i.ibb.co/sbgfbBv/coca-cola-bottiglia.jpg",
    ],
    [
        "restaurant_id" => 8,
        "course_id" => 6,
        "name" => "Moretti",
        "slug" => "moretti-2",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Birra Moretti da 33cl",
        "ingredients" => "birra Moretti",
        "image" => "https://i.ibb.co/NVTdxCb/moretti.jpg",
    ],

    [
        "restaurant_id" => 9,
        "course_id" => 1,
        "name" => "Edamame al vapore",
        "slug" => "edamame-al-vapore",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Edamame al vapore, porzione singola",
        "ingredients" => "Edamame",
        "image" => "https://i.ibb.co/y0vPM2w/edamame.jpg",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 1,
        "name" => "Involtini primavera",
        "slug" => "involtini-primavera",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Involtini primavera porzione da 2 pezzi",
        "ingredients" => "Cavolo cappuccio, cipolle bianche, carote",
        "image" => "https://i.ibb.co/k1Z9Z19/Involtini-primavera.jpg",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 7,
        "name" => "Roll Avocado",
        "slug" => "roll-avocado",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Avocado con riso per sushi avvolto nel nori",
        "ingredients" => "Riso, avocado, alga nori",
        "image" => "https://i.ibb.co/nLZ9B6C/rolls-avocado.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 7,
        "name" => "Roll Rainbow",
        "slug" => "roll-rainbow",
        "price" => 10.00,
        "visible" => 1,
        "description" => "Rainbow roll con tonno, spigola, salmone, gamberetti e avocado.",
        "ingredients" => "Riso, avocado, tonno, spigola, salmone",
        "image" => "https://i.ibb.co/fxNsKFY/roll-rainbow.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 7,
        "name" => "Spicy Salmon Roll",
        "slug" => "spicy-salmon-roll",
        "price" => 10.00,
        "visible" => 1,
        "description" => "Salmone piccante con riso per sushi avvolto nel nori.",
        "ingredients" => "Riso, salmone, alga nori",
        "image" => "https://i.ibb.co/MSBJq9g/spicy-roll.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 7,
        "name" => "Nigiri Gambero",
        "slug" => "nigiri-gambero",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Due pezzi di gambero su riso per sushi pressato.",
        "ingredients" => "Riso, gamberi",
        "image" => "https://i.ibb.co/nwdpNJT/nigiri-gambero.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 6,
        "name" => "Tè Verde senza zucchero giapponese",
        "slug" => "te-verde",
        "price" => 3.00,
        "visible" => 1,
        "description" => "Tè Verde senza zucchero giapponese da 33cl.",
        "ingredients" => "tè verde",
        "image" => "https://i.ibb.co/nwdpNJT/nigiri-gambero.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 5,
        "name" => "Dorayaki",
        "slug" => "dorayaki",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pancake giapponese ripieno di marmellata azuki",
        "ingredients" => "marmellata azuki",
        "image" => "https://i.ibb.co/H4YDjNY/dorayaki-c.jpg",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 3,
        "name" => "Ravioli di gamberi alla griglia",
        "slug" => "ravioli-di-gamberi-griglia",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Ravioli di gamberi alla griglia, porzione da 4 pezzi",
        "ingredients" => "Tofu, funghi, bambù, porro e gamberi",
        "image" => "https://i.ibb.co/5MK1D1J/ravioli-gamberi-piastra.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 3,
        "name" => "Ravioli di manzo al vapore",
        "slug" => "ravioli-di-manzo-vapore",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Ravioli di manzo al vapore porzione da 4",
        "ingredients" => "Verza, porro, zenzero, manzo e salsa di soia",
        "image" => "https://i.ibb.co/5G7LmW5/ravioli-manzo.png",
    ],
    [
        "restaurant_id" => 9,
        "course_id" => 3,
        "name" => "Ravioli di verdure al vapore",
        "slug" => "ravioli-di-verdure-vapore",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Ravioli di verdure al vapore porzione da 4",
        "ingredients" => "Carote, funghi, bambu, tofu e spinaci, vegetariano",
        "image" => "https://i.ibb.co/c6rqCKf/ravioli-verdure.png",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 1,
        "name" => "Fiori di zucca fritti",
        "slug" => "fiori-di-zucca-fritti",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Fiori di zucca farciti e fritti porzione da 4 pezzi",
        "ingredients" => "Fiori di zucca, mozzarella, alici",
        "image" => "https://i.ibb.co/k5WjQ0y/fiori-di-zucca-farciti.jpg",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 1,
        "name" => "Involtini primavera",
        "slug" => "involtini-primavera-2",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Involtini primavera porzione da 2 pezzi, salsa agrodolce inclusa",
        "ingredients" => "Cavolo cappuccio, cipolle bianche, carote",
        "image" => "https://i.ibb.co/k1Z9Z19/Involtini-primavera.jpg",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 7,
        "name" => "Pizza marinara",
        "slug" => "pizza-marinara-2",
        "price" => 5.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "pomodoro, aglio, origano",
        "image" => "https://i.ibb.co/jTDCcGs/pizza-marinara.jpg",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 7,
        "name" => "Margherita con prosciutto crudo",
        "slug" => "margherita-con-prosciutto",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pizza margherita con prosciuuto crudo",
        "ingredients" => "Pomodoro, mozzarella, prosciutto crudo, basilico",
        "image" => "https://i.ibb.co/2cwt10z/pizza-prosciutto.jpg",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 2,
        "name" => "Spaghetti al pomodoro",
        "slug" => "spaghetti-al-pomodoro-2",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Spaghetti al pomodoro, con pomodorini freschi",
        "ingredients" => "Spaghetti, sugo di pomodoro a pezzi, basilico",
        "image" => "https://i.ibb.co/T8Bf2jB/spaghetti-al-pomodoro.jpg",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 2,
        "name" => "Riso saltato con le verdure",
        "slug" => "riso-con-verdure",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Riso saltato con verdure",
        "ingredients" => "Carote, verza e uova, vegetariano",
        "image" => null,
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 2,
        "name" => "Riso alla cantonese",
        "slug" => "riso-alla-cantonese",
        "price" => 4.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "Carote, porro, uova e prosciutto cotto",
        "image" => null,
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 3,
        "name" => "Crêpe pollo fritto",
        "slug" => "crepe-pollo-fritto",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Fritella croccante di farina, coriandolo, insalata iceberg, porro, uovo, pollo fritto e salsa crêpe artigianale",
        "ingredients" => "insalata iceberg, porro, uovo, pollo fritto",
        "image" => null,
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 6,
        "name" => "Peroni",
        "slug" => "peroni-3",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Birra Peroni da 33cl",
        "ingredients" => "peroni",
        "image" => "https://i.ibb.co/wB9n6KG/peroni.jpg",
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 6,
        "name" => "Acqua naturale",
        "slug" => "acqua-naturale-3",
        "price" => 2.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua naturale",
        "image" => null,
    ],
    [
        "restaurant_id" => 10,
        "course_id" => 5,
        "name" => "Tiramisù",
        "slug" => "tiramisu-2",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Tiramisù monoporzione",
        "ingredients" => "uova, mascarpone",
        "image" => "https://i.ibb.co/7tYpqgd/tiramisu.png",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 1,
        "name" => "Supplì",
        "slug" => "suppli",
        "price" => 3.00,
        "visible" => 1,
        "description" => "Suppì al telefono, pezzi 3",
        "ingredients" => "Riso al ragù, mozzarella",
        "image" => "https://i.ibb.co/wQmzVPL/suppli-al-telefono.jpg",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 1,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-4",
        "price" => 3.00,
        "visible" => 1,
        "description" => "Patatine fritte 1 porzione",
        "ingredients" => "patate",
        "image" => "https://i.ibb.co/j8vJdXR/patatine-fritte-4.jpg",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 7,
        "name" => "Burrito vegetariano",
        "slug" => "burrito-vegetariano",
        "price" => 5.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "riso, carote, insalata iceberg, pomodori, fagioli neri, cipolla rossa",
        "image" => "https://i.ibb.co/3TD8hNm/gamberi-piastra.jpg",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 7,
        "name" => "Quesadillas con prosciutto",
        "slug" => "quesadillas-prosiutto",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Quesadillas con prosciutto 2 pezzi",
        "ingredients" => "prosciutto cotto, formaggio cheddar",
        "image" => "https://i.ibb.co/Jn3cbmC/quesadillas-de-jam-n-y-queso-cheddar.jpg",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 1,
        "name" => "Nachos con pico de gallo",
        "slug" => "nachos-pico-de-gallo",
        "price" => 4.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "nachos, pomodorini, cipolla, prezzemolo",
        "image" => "https://i.ibb.co/KFghGzQ/pico-de-gallo-nachos.jpg",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 1,
        "name" => "Pizza Margherita",
        "slug" => "pizza-margherita-4",
        "price" => 5.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "pomodoro, mozzarella",
        "image" => "https://i.ibb.co/5k7tYqH/pizza-margherita.jpg",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 7,
        "name" => "Pizza alla diavola",
        "slug" => "pizza-alla-diavola",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pizza alla diavola",
        "ingredients" => "pomodoro, mozzarella, saleme piccante",
        "image" => "https://i.ibb.co/b2gHGGS/pizza-diavola.png",
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 3,
        "name" => "Tinga",
        "slug" => "tinga",
        "price" => 9.00,
        "visible" => 1,
        "description" => "Pollo sfilacciato in salsa chipotle, pomodoro, cipolla e spezie, guarnito con lattuga e avocado",
        "ingredients" => "Pollo, pomodoro, cipolla, avocado",
        "image" => null,
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 1,
        "name" => "Campechano",
        "slug" => "campechano",
        "price" => 11.00,
        "visible" => 1,
        "description" => "Mix di carne di manzo tagliata a striscioline e chorizo, guarnito con lattuga, cipolla e peperoncino jalapeno soffritto",
        "ingredients" => "Carne di manzo, chorizo,jalapeno",
        "image" => null,
    ],
    [
        "restaurant_id" => 11,
        "course_id" => 1,
        "name" => "Pan de elote",
        "slug" => "pan-de-elote",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Tradizionale torta di mais 1pz",
        "ingredients" => "mais, uova, latte condensato",
        "image" => "https://i.ibb.co/t4238Kv/pan-de-elote.jpg",
    ],

    [
        "restaurant_id" => 12,
        "course_id" => 1,
        "name" => "Bruschetta al pomodoro",
        "slug" => "bruschetta-al-pomodoro",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Bruschetta al pomodoro porzione da 2 pezzi",
        "ingredients" => "Pane integrale, pomodori San Marzano",
        "image" => "https://i.ibb.co/stbspPq/bruschetta-al-pomodoro.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 1,
        "name" => "Involtini primavera",
        "slug" => "involtini-primavera-3",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Involtini primavera porzione da 2 pezzi, salsa agrodolce inclusa",
        "ingredients" => "Cavolo cappuccio, cipolle bianche, carote",
        "image" => "https://i.ibb.co/k1Z9Z19/Involtini-primavera.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 2,
        "name" => "Riso alla crema di scampi",
        "slug" => "riso-alla-crema-di scampi",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Riso alla crema di scampi, con scampi freschi",
        "ingredients" => "Riso, scampi freschi",
        "image" => "https://i.ibb.co/CzX6PSn/riso-scampi-2.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 2,
        "name" => "Spaghetti di riso con verdure",
        "slug" => "spaghetti-di-riso-con-verdure",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Spaghetti di riso con verdure",
        "ingredients" => "Spaghetti di riso, carote, zucchine, verza, germogli di soia",
        "image" => "https://i.ibb.co/7Wx2syP/spaghetti-di-riso-con-verdure.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 3,
        "name" => "Insalata di mare",
        "slug" => "insalata-di-mare",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Insalata di mare",
        "ingredients" => "Gamberi, cozze, seppai, calamari, carote, sedano, olive nere",
        "image" => "https://i.ibb.co/6D1kM1p/insalata-di-mare-1.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 3,
        "name" => "Gamberi alla piastra",
        "slug" => "gamberi-alla-piastra",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Gamberi alla piastra",
        "ingredients" => "Gamberi freschi",
        "image" => "https://i.ibb.co/DQsVvxc/gamberi-piastra.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 4,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-5",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Patatine fritte",
        "ingredients" => "Patate, rosmarino",
        "image" => "https://i.ibb.co/1nn9MR1/patatine-fritte-5.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 6,
        "name" => "Peroni",
        "slug" => "peroni-4",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Birra Peroni da 33cl",
        "ingredients" => "peroni",
        "image" => "https://i.ibb.co/wB9n6KG/peroni.jpg",
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 6,
        "name" => "Acqua naturale",
        "slug" => "acqua-naturale-4",
        "price" => 2.00,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua naturale",
        "image" => null,
    ],
    [
        "restaurant_id" => 12,
        "course_id" => 6,
        "name" => "Acqua frizzante",
        "slug" => "acqua-frizzante-3",
        "price" => 2.50,
        "visible" => 1,
        "description" => null,
        "ingredients" => "Acqua frizzante",
        "image" => null,
    ],

    [
        "restaurant_id" => 13,
        "course_id" => 6,
        "name" => "Coca cola",
        "slug" => "coca-cola-5",
        "price" => 2.50,
        "visible" => 1,
        "description" => "Coca Cola in lattina da 33cl",
        "ingredients" => "coca cola",
        "image" => "https://i.ibb.co/5vrF5yT/coca-cola-lattina.jpg",
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Pizza Margherita",
        "slug" => "pizza-margherita-5",
        "price" => 5.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "pomodoro, mozzarella",
        "image" => "https://i.ibb.co/MDDfDhq/pizza-margherita-1.jpg",
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Hamburger Americano",
        "slug" => "hamburger-americano-2",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Hamburger Americano con salse a scelta",
        "ingredients" => "carne di manzo,pomodoro, formaggio sottiletta",
        "image" => null,
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Hamburger Vegetariano",
        "slug" => "hamburger-vegetariano",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Hamburger Vegetariano con salse a scelta",
        "ingredients" => "hamburger vegetariano,pomodoro, formaggio sottiletta, insalata iceberg",
        "image" => null,
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Hamburger di pesce",
        "slug" => "hamburger-pesce",
        "price" => 6.50,
        "visible" => 1,
        "description" => "Hamburger di pesce con salse a scelta",
        "ingredients" => "merluzzo ,pomodoro, formaggio sottiletta, insalata iceberg",
        "image" => null,
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Hamburger di pollo",
        "slug" => "hamburger-pollo",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Hamburger di pollo con salse a scelta",
        "ingredients" => "pollo ,pomodoro, formaggio sottiletta, insalata iceberg",
        "image" => null,
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Pizza capricciosa",
        "slug" => "pizza-capricciosa",
        "price" => 5.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "pomodoro, mozzarella, funghetti, carciofini, olive nere",
        "image" => "https://i.ibb.co/j3bzLsx/pizza-capricciosa-2.jpg",
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Pizza con patate al forno",
        "slug" => "pizza-con-patate-al-forno",
        "price" => 6.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "mozzarella, patate al forno, rosmarino",
        "image" => "https://i.ibb.co/BjJm4SY/Pizza-Mozzarella-e-Rosmarino-Fotor.jpg",
    ],
    [
        "restaurant_id" => 13,
        "course_id" => 7,
        "name" => "Pizza quattro formaggi",
        "slug" => "pizza-quattro-formaggi-2",
        "price" => 6.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "mozzarella, stracchino, pecorino, grana padano",
        "image" => "https://i.ibb.co/3vt1QhC/pizza-quattro-formaggi.jpg",
    ],
    [
        "restaurant_id" => 7,
        "course_id" => 6,
        "name" => "Moretti",
        "slug" => "moretti-3",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Birra Moretti da 33cl",
        "ingredients" => "birra Moretti",
        "image" => "https://i.ibb.co/NVTdxCb/moretti.jpg",
    ],

    [
        "restaurant_id" => 14,
        "course_id" => 6,
        "name" => "Coca cola",
        "slug" => "coca-cola-6",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Coca Cola in lattina da 33cl",
        "ingredients" => "coca cola",
        "image" => "https://i.ibb.co/5vrF5yT/coca-cola-lattina.jpg",
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 1,
        "name" => "Baccalà fritto e patatine",
        "slug" => "baccala-fritto-e-pataine",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Baccalà fritto con patatine, 1 porzione",
        "ingredients" => "baccalà, patate",
        "image" => "https://i.ibb.co/YLmKNHM/baccala-fritto.jpg",
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 2,
        "name" => "Linguine al farro alla pescatora",
        "slug" => "linguine-al-farro-alla-pescatora",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Linguine al farro alla pescatora",
        "ingredients" => "Linguine al farro, cozze, vongole, pomodorini, prezzemolo",
        "image" => "https://i.ibb.co/hgsmFbD/linguine-pescatora.jpg",
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 3,
        "name" => "Insalata di calamari",
        "slug" => "insalata-di-calamari",
        "price" => 6.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "Calamari, seppie, cozze, gamberetti, olive nere, sedano, carote",
        "image" => "https://i.ibb.co/6D1kM1p/insalata-di-mare-1.jpg",
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 2,
        "name" => "Spaghetti allo scoglio",
        "slug" => "spaghetti-allo-scoglio-2",
        "price" => 6.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "Spaghetti, gamberi, olive, vongole, telline",
        "image" => "https://i.ibb.co/vQtrfsN/spaghetti-allo-scoglio.jpg",
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 7,
        "name" => "Tris di roll",
        "slug" => "triss-di-roll",
        "price" => 8.50,
        "visible" => 7,
        "description" => "Triss di roll, salmone, tonno, spigola. Due pezzi per gusto",
        "ingredients" => "Riso, salmone, tonno, spigola",
        "image" => "https://i.ibb.co/fxNsKFY/roll-rainbow.png",
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 7,
        "name" => "Nigiri Salmone",
        "slug" => "nigiri-salmone-2",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Nigiri con salmone, 2 pezzi",
        "ingredients" => "riso, salmone",
        "image" => "https://images.unsplash.com/photo-1611810175440-aec1ef36d8c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 7,
        "name" => "Uramaki California",
        "slug" => "uramaki-california-2",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Uramaki con Surimi, Tonno e Panna",
        "ingredients" => "riso, polpa di granchio, tonno, panna, ikura",
        "image" => "https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 7,
        "name" => "Tempura di Gamberi",
        "slug" => "tempura-di-gamberi-2",
        "price" => 9.50,
        "visible" => 1,
        "description" => "Gamberi fritti",
        "ingredients" => "gamberi, panko",
        "image" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/tempura-di-gamberi.jpg?itok=-JjFZyK8"
    ],
    [
        "restaurant_id" => 14,
        "course_id" => 5,
        "name" => "Mochi alla fragola",
        "slug" => "mochi-alla-fragola",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Un dolce che unisce la tradizione giapponese ai dessert di origine occidentale: il mochi con fragole e azuki (ichigo daifuku)",
        "ingredients" => "fragole, pasta di fagioli dolci, farina di riso",
        "image" => "https://i.ibb.co/MSC2wm5/Mochi-alla-fragola.jpg"
    ],


    [
        "restaurant_id" => 15,
        "course_id" => 1,
        "name" => "Samosa di sgombro",
        "slug" => "samosa-di-sgombro",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Samosa di sgombro patate e spezie",
        "ingredients" => "sgombro, patate, spezie",
        "image" => "https://i.ibb.co/9yqjcKX/Samosa-di-sgombro-patate-e-spezie.jpg"
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 1,
        "name" => "Uttapam vegetale",
        "slug" => "uttapam-vegetale",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Pancakes del sud dell'India",
        "ingredients" => "lenticchie, riso, cipolla, erbe",
        "image" => "https://i.ibb.co/cwG4T9v/vegetable-uttapam.jpg"
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 1,
        "name" => "Vegetable pakora",
        "slug" => "vetgetale-pakora",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Misto delle verdure coperto con farina di ceci",
        "ingredients" => "farina di ceci, carote, piselli, cipolla",
        "image" => null,
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 1,
        "name" => "Chicken pakora",
        "slug" => "chicken-pakora",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pezzi di pollo coperti con farina di ceci",
        "ingredients" => "pollo, farina di ceci",
        "image" => null,
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 2,
        "name" => "Tandoor chicken",
        "slug" => "tandoor-chicken",
        "price" => 12.00,
        "visible" => 1,
        "description" => "Pollo marinato con erbe, spezie indiane e yogurt cucinato in tandoor",
        "ingredients" => "pollo, yogurt, spezie indiane",
        "image" => "https://i.ibb.co/tp5W0Nk/tandoori-chicken.jpg"
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 2,
        "name" => "Fish tikka",
        "slug" => "fish-takka",
        "price" => 14.00,
        "visible" => 1,
        "description" => "Salmone marinato in erbe fresche orientali e grigliato in tandoori",
        "ingredients" => "salmone, erbe",
        "image" => null,
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 4,
        "name" => "Aloo gobhi",
        "slug" => "aloo-gobhi",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Patate e cavolfiori cucinati in stile indiano",
        "ingredients" => "patate, cavolfiore",
        "image" => null,
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 5,
        "name" => "Kulfi pista",
        "slug" => "kulfi-pista",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Gelato tipico indiano con pistacchio",
        "ingredients" => "gelato al pistacchio",
        "image" => null,
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 7,
        "name" => "Pizza Margherita",
        "slug" => "pizza-margherita-6",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pizza margherita",
        "ingredients" => "Pomodoro, mozzarella, basilico",
        "image" => "https://images.unsplash.com/photo-1564936281291-294551497d81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1052&q=80"
    ],
    [
        "restaurant_id" => 15,
        "course_id" => 5,
        "name" => "Acqua naturale",
        "slug" => "acqua-naturale-5",
        "price" => 2.00,
        "visible" => 1,
        "description" => "Acqua naturale 50cl",
        "ingredients" => "acqua",
        "image" => null,
    ],

    [
        "restaurant_id" => 16,
        "course_id" => 7,
        "name" => "Pizza Margherita",
        "slug" => "pizza-margherita-7",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Pizza margherita",
        "ingredients" => "Pomodoro, mozzarella, basilico",
        "image" => "https://i.ibb.co/5k7tYqH/pizza-margherita.jpg"
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 1,
        "name" => "Papad",
        "slug" => "papad",
        "price" => 1.50,
        "visible" => 1,
        "description" => "Farina di lenticchie e spezie indiane",
        "ingredients" => "Farina di lenticchie e spezie indiane",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 1,
        "name" => "Samosa patate e piselli",
        "slug" => "samosa-patate-piselli",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Involtino di patate e piselli",
        "ingredients" => "patate, piselli",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 1,
        "name" => "Fried onion rings",
        "slug" => "fried-onion-rings",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Anelli di cipolla fritti",
        "ingredients" => "cipolla",
        "image" => "https://i.ibb.co/CQfqvMq/onion-bhajis.jpg"
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 4,
        "name" => "Prawn pakora",
        "slug" => "prawn-pakora",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Pezzi di gamberi fritti",
        "ingredients" => "gamberi",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 4,
        "name" => "Baingan bharta",
        "slug" => "baingan-bharta",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Melanzane affumicate stile indiano",
        "ingredients" => "melanzane",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 3,
        "name" => "Fish curry",
        "slug" => "fish-curry",
        "price" => 14.00,
        "visible" => 1,
        "description" => "Pesce al curry",
        "ingredients" => "merluzzo, spezie",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 3,
        "name" => "Prawn masala",
        "slug" => "prawn-masala",
        "price" => 16.00,
        "visible" => 1,
        "description" => "Gamberi cucinati con spezie fresche",
        "ingredients" => "gamberi, spezie",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 2,
        "name" => "Prawn biryani",
        "slug" => "prawn-biryani",
        "price" => 15.50,
        "visible" => 1,
        "description" => "Riso con gamberi e salsa varie",
        "ingredients" => "riso basmati, gamberi, salsa",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 2,
        "name" => "Vegetable pulao",
        "slug" => "vegetable-pulao",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Riso basmati con verdure miste frutta secca",
        "ingredients" => "riso basmati, verdure miste, frutta secca",
        "image" => null,
    ],
    [
        "restaurant_id" => 16,
        "course_id" => 5,
        "name" => "Gulab jamun",
        "slug" => "gulab-jamun",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Dolce tipico della cucina indiana e pakistana.",
        "ingredients" => " latte in polvere, burro, cardamomo, mandorle",
        "image" => "https://i.ibb.co/VjxmZMN/gulab-jamun.jpg"
    ],

    [
        "restaurant_id" => 17,
        "course_id" => 1,
        "name" => "Supplì",
        "slug" => "suppli-2",
        "price" => 2.50,
        "visible" => 1,
        "description" => "Suppli, 2 pezzi",
        "ingredients" => "riso, mozzarella",
        "image" => "https://i.ibb.co/wQmzVPL/suppli-al-telefono.jpg"
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 1,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-6",
        "price" => 3.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "patate",
        "image" => "https://i.ibb.co/1vDCN5g/patatine-fritte-2.jpg"
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 1,
        "name" => "Fiori di zucca fritti ripieni",
        "slug" => "fiori-di-zucca-fritti-ripieni",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Fiori di zucca ripieni di mozzarella e alici, 2 pezzi",
        "ingredients" => "fiori di zucca, mozzarella, alici",
        "image" => "https://i.ibb.co/k5WjQ0y/fiori-di-zucca-farciti.jpg",
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 3,
        "name" => "Arrosticini",
        "slug" => "arrosticini-2",
        "price" => 8.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "carne di pecora",
        "image" => "https://i.ibb.co/5xN8hZ9/arrosticini.jpg"
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 3,
        "name" => "Bistecca alla fiorentina",
        "slug" => "bistecca-alla-fiorentina",
        "price" => 15.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "carne di vitellone",
        "image" => "https://i.ibb.co/0szsnjm/bistecca-classica-alla-fiorentina.jpg"
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 7,
        "name" => "Pizza quattro stagioni",
        "slug" => "pizza-quattro-stagioni-2",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pizza quattro stagioni",
        "ingredients" => "Mozzarella, origano, pomodoro, carciofini, olive nere, prosciutto",
        "image" => "https://i.ibb.co/qpD3mfX/pizza-capricciosa.jpg",
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 7,
        "name" => "Pizza Margherita",
        "slug" => "pizza-margherita-8",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Pizza margherita",
        "ingredients" => "Pomodoro, mozzarella, basilico",
        "image" => "https://i.ibb.co/5k7tYqH/pizza-margherita.jpg"
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 7,
        "name" => "Pizza alla diavola",
        "slug" => "pizza-diavola-2",
        "price" => 8.50,
        "visible" => 1,
        "description" => "Pizza alla diavola",
        "ingredients" => "Mozzarella, pomodoro, salame piccante",
        "image" => "https://i.ibb.co/b2gHGGS/pizza-diavola.png",
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 7,
        "name" => "Pizza quattro formaggi",
        "slug" => "pizza-quattro-formaggi-3",
        "price" => 7.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "mozzarella, stracchino, pecorino, grana padano",
        "image" => "https://i.ibb.co/3vt1QhC/pizza-quattro-formaggi.jpg",
    ],
    [
        "restaurant_id" => 17,
        "course_id" => 7,
        "name" => "Pizza marinara",
        "slug" => "pizza-marinara-3",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pizza marinara",
        "ingredients" => "Pomodoro, aglio, origano, olio",
        "image" => "https://i.ibb.co/jTDCcGs/pizza-marinara.jpg",
    ],


    [
        "restaurant_id" => 18,
        "course_id" => 5,
        "name" => "Panna cotta",
        "slug" => "panna-cotta",
        "price" => 5.50,
        "visible" => 1,
        "description" => "Panna cotta vegana",
        "ingredients" => "Panna di soia, sciroppo di cioccolato, granella d frutta secca",
        "image" => "https://i.ibb.co/9s2gTN2/panna-cotta-veg.png"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 1,
        "name" => "Barchetta di melanzane",
        "slug" => "barchetta-di-melanzane",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Melanzane ripiene con verdure miste, 2 pezzi.",
        "ingredients" => "melanzane, verdure miste,",
        "image" => "https://i.ibb.co/1M4gd78/melanzane-ripiene.jpg"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 1,
        "name" => "Insalata di funngi",
        "slug" => "insalata-di-funghi",
        "price" => 2.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "Insalata lattughino, funghi champignon, pomodori, vinaigrette",
        "image" => "https://i.ibb.co/17vcQ9z/insalata-funghi.jpg"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 1,
        "name" => "Felafel con hummus",
        "slug" => "felafel-con-hummus",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Felafel di ceci con hummus",
        "ingredients" => "ceci",
        "image" => "https://i.ibb.co/qk2H9jb/felafel-hummus.jpg"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 2,
        "name" => "Carbonara vegana",
        "slug" => "carbonara-vegana",
        "price" => 7.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "seitan, panna di soia",
        "image" => "https://i.ibb.co/g9gNZNF/carbonara-veg.png"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 3,
        "name" => "Arrosto di seitan",
        "slug" => "arrosto di seitan",
        "price" => 7.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "seitan, arancia, uvetta",
        "image" => "https://i.ibb.co/Z24N6YW/arrosto-seitan-arancia-uvetta.png"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 1,
        "name" => "Carpacco di seitan",
        "slug" => "carpaccio-di-seitan",
        "price" => 8.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "Saitan, gondino, rughetta",
        "image" => "https://i.ibb.co/1qbQrsz/carpaccio-seitan.png"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 1,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-7",
        "price" => 4.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "patate",
        "image" => "https://i.ibb.co/X8RWnVP/patatine-fritte-1.jpg"
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 5,
        "name" => "Beck's",
        "slug" => "becks-2",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Birra Beck's da 33cl",
        "ingredients" => "Beck's",
        "image" => null,
    ],
    [
        "restaurant_id" => 18,
        "course_id" => 7,
        "name" => "Pizza marinara",
        "slug" => "pizza-marinara-4",
        "price" => 6.50,
        "visible" => 1,
        "description" => "Pizza marinara, a richiesta con farina di farro",
        "ingredients" => "Pomodoro, aglio, origano, olio",
        "image" => "https://i.ibb.co/jTDCcGs/pizza-marinara.jpg",
    ],
    [
        "restaurant_id" => 5,
        "course_id" => 6,
        "name" => "Coca-cola",
        "slug" => "coca-cola-7",
        "price" => 3.00,
        "visible" => 1,
        "description" => "bottiglia da 1.5lt",
        "ingredients" => "Coca-cola",
        "image" => null,
    ],


    [
        "restaurant_id" => 20,
        "course_id" => 6,
        "name" => "Coca-cola",
        "slug" => "coca-cola-8",
        "price" => 3.00,
        "visible" => 1,
        "description" => "bottiglia da 1.5lt",
        "ingredients" => "Coca-cola",
        "image" => "https://i.ibb.co/sbgfbBv/coca-cola-bottiglia.jpg",
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 7,
        "name" => "Nigiri Salmone",
        "slug" => "nigiri-salmone-3",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Nigiri con salmone nostrano",
        "ingredients" => "riso, salmone",
        "image" => "https://images.unsplash.com/photo-1611810175440-aec1ef36d8c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 7,
        "name" => "Uramaki Salmone Avocado",
        "slug" => "uramaki-salmone-avocado-2",
        "price" => 8.00,
        "visible" => 1,
        "description" => "Uramaki classico",
        "ingredients" => "riso, salmone, avocado, alga nori",
        "image" => "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 7,
        "name" => "Pollo Teriyaki",
        "slug" => "pollo-teriyaki-2",
        "price" => 7.00,
        "visible" => 1,
        "description" => "Pollo in salsa teriyaki",
        "ingredients" => "pollo, salsa teriyaki, cipollotto",
        "image" => "https://images.unsplash.com/photo-1609183480237-ccbb2d7c5772?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 7,
        "name" => "Spicy Salmon Roll",
        "slug" => "spicy-salmon-roll-2",
        "price" => 10.00,
        "visible" => 1,
        "description" => "Salmone piccante con riso per sushi avvolto nel nori.",
        "ingredients" => "Riso, salmone, alga nori",
        "image" => "https://i.ibb.co/MSBJq9g/spicy-roll.png",
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 3,
        "name" => "Ravioli di manzo al vapore",
        "slug" => "ravioli-di-manzo-vapore-2",
        "price" => 5.00,
        "visible" => 1,
        "description" => "Ravioli di manzo al vapore porzione da 4",
        "ingredients" => "Verza, porro, zenzero, manzo e salsa di soia",
        "image" => "https://i.ibb.co/5G7LmW5/ravioli-manzo.png",
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 7,
        "name" => "Huevos rancheros",
        "slug" => "huevos-rancheros-2",
        "price" => 6.00,
        "visible" => 1,
        "description" => "",
        "ingredients" => "tortilla di mais, uova, fagioli neri, salsa di pomodoro",
        "image" => "https://bellyfull.net/wp-content/uploads/2021/04/Huevos-Rancheros-blog-768x1024.jpg"
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 1,
        "name" => "Tacos tricorito",
        "slug" => "tacos-tricorito",
        "price" => 5.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "canrne, pesce, verdure miste, formagio cheddar",
        "image" => "https://i.ibb.co/mDwb4tB/tacos-tricorito.jpg"
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 2,
        "name" => "Chili veg",
        "slug" => "chili-veg",
        "price" => 7.50,
        "visible" => 1,
        "description" => "",
        "ingredients" => "verdure miste, fagioli neri, mais",
        "image" => "https://i.ibb.co/7vbsn6w/chili-veg.jpg"
    ],
    [
        "restaurant_id" => 19,
        "course_id" => 5,
        "name" => "Dorayaki",
        "slug" => "dorayaki-2",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Pancake giapponese ripieno di marmellata azuki",
        "ingredients" => "marmellata azuki",
        "image" => "https://i.ibb.co/H4YDjNY/dorayaki-c.jpg",
    ],

    [
        "restaurant_id" => 20,
        "course_id" => 5,
        "name" => "Coca Cola",
        "slug" => "coca-cola-9",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Coca Cola da 33cl",
        "ingredients" => "Coca Cola",
        "image" => "https://i.ibb.co/5vrF5yT/coca-cola-lattina.jpg",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 6,
        "name" => "Coca-cola",
        "slug" => "coca-cola-10",
        "price" => 3.00,
        "visible" => 1,
        "description" => "bottiglia da 1.5lt",
        "ingredients" => "Coca-cola",
        "image" => "https://i.ibb.co/sbgfbBv/coca-cola-bottiglia.jpg",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 5,
        "name" => "Tiramisù",
        "slug" => "tiramisu-3",
        "price" => 4.00,
        "visible" => 1,
        "description" => "Tiramisù fatto in casa",
        "ingredients" => "Mascarpone, savoiardi, caffè, uova, zucchero",
        "image" => "https://images.unsplash.com/photo-1631206753348-db44968fd440?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 6,
        "name" => "Moretti",
        "slug" => "moretti-4",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Birra Moretti da 33cl",
        "ingredients" => "birra Moretti",
        "image" => "https://i.ibb.co/NVTdxCb/moretti.jpg",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 7,
        "name" => "Double Ham",
        "slug" => "double-ham-2",
        "price" => 10.50,
        "visible" => 1,
        "description" => "Hamburger con 2 fette di manzo (salse a scelta)",
        "ingredients" => "Manzo, cipolla, insalata, pomodori, pane da hamburger, cheddar",
        "image" => "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1899&q=80",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 7,
        "name" => "Egg Burger",
        "slug" => "egg-burger-2",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Hamburger con uovo e maiale alla piastra",
        "ingredients" => "Uovo, insalata, carne suina, cheddar, pane ai semi misti",
        "image" => "https://images.pexels.com/photos/6348082/pexels-photo-6348082.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 7,
        "name" => "Double Cheese Burger",
        "slug" => "double-cheese-burger",
        "price" => 10.50,
        "visible" => 1,
        "description" => "Doppio cheese burger di manzo con formaggio cheddar",
        "ingredients" => "Manzo, insalata, pomodori, cheddar, cipolle, pane da hamburger",
        "image" => "https://images.pexels.com/photos/5948790/pexels-photo-5948790.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 7,
        "name" => "Hamburger Vegetariano",
        "slug" => "hamburger-vegetariano-2",
        "price" => 6.00,
        "visible" => 1,
        "description" => "Hamburger Vegetariano con salse a scelta",
        "ingredients" => "hamburger vegetariano,pomodoro, formaggio sottiletta, insalata iceberg",
        "image" => null,
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 1,
        "name" => "Patatine fritte",
        "slug" => "patatine-fritte-8",
        "price" => 3.50,
        "visible" => 1,
        "description" => "Patate fritte con salsa a scelta",
        "ingredients" => "patate",
        "image" => "https://i.ibb.co/1vDCN5g/patatine-fritte-2.jpg"
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 1,
        "name" => "Bruschetta al pomodoro",
        "slug" => "bruschetta-pomodoro-2",
        "price" => 4.50,
        "visible" => 1,
        "description" => "Bruschetta di pane fresco con pomodori Ciliegini",
        "ingredients" => "Pane fresco, pomodorini, olio, basilico",
        "image" => "https://i.ibb.co/stbspPq/bruschetta-al-pomodoro.jpg",
    ],
    [
        "restaurant_id" => 20,
        "course_id" => 7,
        "name" => "Hamburger di pollo",
        "slug" => "hamburger-pollo-2",
        "price" => 7.50,
        "visible" => 1,
        "description" => "Hamburger di pollo con salse a scelta",
        "ingredients" => "pollo ,pomodoro, formaggio sottiletta, insalata iceberg",
        "image" => null,
    ],
];
